version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - LLM_PROVIDER=openai

#  test:
#    build:
#      context: .
#      dockerfile: Dockerfile.integration-tests
#    depends_on:
#      - app
#    environment:
#      - API_URL=http://app:8000
